### ISSUE TITLE
Not getting the /secret-menu

### ISSUE THREAD

**Issue by emikuszewski** [spring-cloud-services-samples/cook#10]
Hey Team,

Ran through the setup in the repo as well as well an additional step of: 'cf set-env cook SPRING_PROFILES_ACTIVE dev,encryption'

/restaurants works, though the /secret-menu is just returning the encrypted content. Check it out here: https://cookie-em.cfapps.io/restaurant/secret-menu.

I can do a Postman on it and can see it should be tacos, but not through the browser. Thoughts?

Thanks!

**Comment by royclarkson** [comment]
I am able to curl the endpoint and see the unencrypted TACOS!!!! response. Please let us know if you are still having issues. Thanks for the feedback!
